package com.financial.ledger.microservices.core.record.domain;

public enum AccountType {
    BANK_CURRENT_ACCOUNT,
    BANK_SAVINGS_ACCOUNT,
    WORKPLACE_PENSION_ACCOUNT,
    SIPP_PENSION_ACCOUNT,
    MONTHLY_SUBSCRIPTION_ACCOUNT,
    ANNUAL_SUBSCRIPTION_ACCOUNT,
    MORTGAGE_COVER_TYPE_ACCOUNT,
    LIFE_INSURANCE_COVER_ACCOUNT,
    LANDLORD_INSURANCE_COVER_ACCOUNT,
    HOUSE_INSURANCE_COVER_ACCOUNT,
    CAR_INSURANCE_COVER_ACCOUNT,
    GAP_CAR_INSURANCE_COVER_ACCOUNT
}
