server.port: 7002
server.error.include-message: always

spring.data.mongodb:
  host: localhost
  port: 27017
  database: portfolio-records-db

spring.cloud.stream:
  defaultBinder: kafka
  default.contentType: application/json
  bindings.input:
    destination: portfoliorecords
    group: portfoliorecordsGroup

spring.cloud.stream.bindings.input.consumer:
  maxAttempts: 3
  backOffInitialInterval: 500
  backOffMaxInterval: 1000
  backOffMultiplier: 2.0
  enableDlq: true

spring.cloud.stream.kafka.binder:
  brokers: 127.0.0.1
  defaultBrokerPort: 9092

logging:
  level:
    root: INFO
    com.financial.ledger.microservices: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"

---
spring.profiles: docker
server.port: 8080
spring.data.mongodb.host: mongodb
spring.cloud.stream.kafka.binder.brokers: kafka